### PR TITLE
Fixed issue #108

### PR DESCRIPTION
**Pull request by Markopp**
Replaced fixed value with a variable

### CODE REVIEW

**Comment by capnmidnight** [comment]
Hi @Markopp, you didn't add yourself to CONTRIBUTORS.md!

**Comment by capnmidnight** [comment]
Cool, thanks!

**Comment by Markopp** [comment]
Glad to help, looking out to do more stuff in the future! 😸

**Comment by capnmidnight** [comment]
That'd be great. If you don't mind, would you email me at sean@notiontheory.com and tell me a bit about your background and what you're hoping to learn from working on open source software? We can chat about how we can make Primrose fit those goals for you.

Thanks again!

**Pull request merged**
