### PR TITLE
Solved issue #135

### PR DESCRIPTION
**Pull request by Markopp**
Moved files to demos directory and made minor changes in code.

### CODE REVIEW

**Comment by capnmidnight** [comment]
Thanks for this. I'll try to get this merged in tomorrow. Sorry for the delay, I've been on baby duty.

There is a weird thing where some packages in the node_modules directory got included in the repo. Any ideas what happened there? The node_modules directory did be ignored by the .gitignore file, so i don't know.

**Comment by Markopp** [comment]
I've found that weird too when I was pushing the changes, but .gitignore does indeed list node_modules directory, so I am not really sure what could've caused the problem.

**Comment by capnmidnight** [comment]
Ah, I see what happened. The .gitignore file got moved to the demos/ directory, so it's not active for the project directory.

**Comment by capnmidnight** [comment]
Was able to get this merged in without trouble. It took doing:

````command-line
git checkout -b Markopp-master master
git pull https://github.com/Markopp/Primrose.git master
git checkout master
git merge --squash Markopp-master
git mv demos/.gitignore ./
git rm -rf node_modules/
````

The first 2 lines are to make a local copy of your code without overwriting my code.

The next two lines take all your changes and copy them on top of my code in one go. Normally, Git will try to copy the commits themselves. This ignores the individual commits and focuses on the end result. It creates a commit, but does not push that commit.

The second to last line moves the .gitignore file back to where it belongs, and in the process modifies the staged commit.

The last line removes the node_modules directory and all of its files from the commit, without removing them from the directory itself.

I wrote a message "Merge @Markopp's fix for Issue #135", then pushed that commit to origin/master.

**Pull request closed without merging**
