### PR TITLE
Fix for issue #122

### PR DESCRIPTION
**Pull request by upodroid**

### CODE REVIEW

**Comment by upodroid** [comment]
:)

**Comment by capnmidnight** [comment]
Hi Upodroid, thanks for taking a crack at this.

First off, my goal is to help you learn. If anything I say is confusing to you, please speak up and ask questions. After 20 years of programming, it's hard to remember what beginning programmers do and do not know, or what sort of pace is too fast or too slow.

If you’re interested in joining the project beyond this PR, please email me at sean@notiontheory.com and tell me a bit about your background and what you're hoping to learn from working on open source software. We can chat about how we can make Primrose fit those goals for you. If you haven’t read it already, there is a page on the wiki about the different Issue labels and a few basic guidelines for working together: https://github.com/NotionTheory/Primrose/wiki/Welcome-to-Primrose

Now, there are a few things we should work on for your pull request.

For starters, you didn't add your name to [CONTRIBUTORS.md](https://github.com/NotionTheory/Primrose/blob/master/CONTRIBUTORS.md)! I'd like to give you credit for the work you do, and that's where it goes. Just add your name and your GitHub handle at the end of the document.

You should be able to commit any changes to your fork of the repository and once you push it, it should become available as part of the pull request. At least, I think that's how it works. If it doesn't, no worries, we'll figure out how to fix it.

I see that you [moved the sky position code to line 344](https://github.com/NotionTheory/Primrose/pull/128/files#diff-f973d0fc3478e2595172f00666f9ab80R344) like I asked. Let's also add a new-line character between the calls to `moveGround();` and `this.sky.position.copy(this.input.head.position);`. It's just a little awkward that way right now. I would only put two code statements on a single line of code like this if they were doing very closely related things, but in this case these two lines of code operate on completely different objects in the scene.

I also see that you [deleted the `if` statement on line 375](https://github.com/NotionTheory/Primrose/pull/128/files#diff-f973d0fc3478e2595172f00666f9ab80L374). That's a good start, but a little bit more needs to be done here. It'd be best to delete what are now lines 374 and 375 out of the file that you have now. We need what is now a duplicate `this.sky.position.copy(this.input.head.position);` call to be deleted, and what is now a trailing `}` curly brace to be deleted.

If you can get those changes done, I'll be able to merge your PR in to the main branch. 

Thanks again!

**Comment by upodroid** [comment]
I'll get the changes done. I'll email you in a bit.

**Comment by upodroid** [comment]
Fixed in a new PR

**Pull request closed without merging**
